"""empty message

Revision ID: 817bdba5846f
Revises: 869c1761d012
Create Date: 2023-01-31 16:20:49.564358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '817bdba5846f'
down_revision = '869c1761d012'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('short_url',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_url', sa.String(length=500), nullable=False),
    sa.Column('short_url', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('short_url')
    )
    op.drop_table('short_urls')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('short_urls',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('original_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('short_url', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='short_urls_pkey'),
    sa.UniqueConstraint('short_url', name='short_urls_short_url_key')
    )
    op.drop_table('short_url')
    # ### end Alembic commands ###
